# -*- coding: utf-8 -*-
"""GenAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQ_NMHUo6COEBX6yyBkEUZBhbYW7At6H
"""

!pip install langchain openai
!pip install pymysql
!pip install langchain-huggingface
!pip install huggingface_hub
!pip install accelerate
!pip install bitsandbytes
!pip install langchain

from langchain_huggingface import HuggingFaceEndpoint

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %load_ext sql

!pip install python-dotenv

import os
os.environ["OPENAI_API_KEY"] = "sk-9tCPgYo2g7JdFERF63ES9HnYRo70BnqikNMO2DZY12T3BlbkFJC-D1l7arCfrx5L2dOkUp4xUTp7GVHmYskXjtvUr7MA"

from google.colab import files
uploaded = files.upload("/content/drive/MyDrive/Dump20250716/Dump20250716")

import zipfile

# Define ZIP file path and extraction location
zip_path = "/content/drive/MyDrive/Dump20250716/Dump20250716/Dump20250716 (7).zip"
extract_to = "/content/sql_extract"  # You can change this if needed

# Extract the zip file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

# Confirm extracted files
import os
print("Extracted files:", os.listdir(extract_to))

import sqlite3

conn = sqlite3.connect("/content/sql_extract/Dump20250716")

import sqlite3
conn = sqlite3.connect("my_database.db")
cursor = conn.cursor()
with open('/content/drive/MyDrive/Dump20250716/Dump20250716/Dump20250716 (4).zip.sql', 'r') as f:
    sql = f.read()
cursor.executescript(sql)
conn.commit()
conn.close()